export const FETCH_CITY_WEATHER_REQUEST = "FETCH_CITY_WEATHER_REQUEST";
export const FETCH_CITY_WEATHER_SUCCESS = "FETCH_CITY_WEATHER_SUCCESS";
export const FETCH_CITY_WEATHER_FAILURE = "FETCH_CITY_WEATHER_FAILURE";